name: Scheduled YouTube Upload

on:
  schedule:
    # - cron: '30 11 * * *'   # 5:00 PM IST
    - cron: '30 7 * * *'   # 1:00 PM IST
  workflow_dispatch:

jobs:
  trigger-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Call uploadVideo API
        run: |
          curl -X POST ${{ secrets.APP_URL }}/api/uploadVideo \
          -H "Authorization: Bearer ${{ secrets.UPLOAD_API_KEY }}"
